<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VAIO_elinochka" name="com.day6.test.TestNGTwoDemensionArrayDataProvider$TwoDemensionArrayDataProvider" tests="1" failures="1" timestamp="12 Oct 2018 18:21:27 GMT" time="0.000" errors="0">
  <testcase name="testTransPoseMatrix1" time="0.000" classname="com.day6.test.TestNGTwoDemensionArrayDataProvider$TwoDemensionArrayDataProvider">
    <failure type="org.testng.TestNGException" message="
Method public void com.day6.test.TestNGTwoDemensionArrayDataProvider$TwoDemensionArrayDataProvider.testTransPoseMatrix1(int,int,int) requires a @DataProvider named : transPoseMatrix1 in class com.day6.test.TestNGTwoDemensionArrayDataProvider$TwoDemensionArrayDataProvider">
      <![CDATA[org.testng.TestNGException: 
Method public void com.day6.test.TestNGTwoDemensionArrayDataProvider$TwoDemensionArrayDataProvider.testTransPoseMatrix1(int,int,int) requires a @DataProvider named : transPoseMatrix1 in class com.day6.test.TestNGTwoDemensionArrayDataProvider$TwoDemensionArrayDataProvider
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:253)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:402)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1358)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1058)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1160)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase>
</testsuite>
